

modif1:
	openscad --autocenter --view axes --render -o modif1.png  modif1.scad

modif2:
	openscad --autocenter --view axes --render -o modif2.png  modif2.scad

all: modif1 modif2

.PHONY: all modif1 modif2
