services:
  app:
    build: ./
    volumes:
      - nas-shared:/home/nas/shared

volumes:
  nas-shared:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.1.171/shared"
      o: "rw,vers={{ smb_vers }},username=guest,password=,uid=1000,gid=1000"
