---
- name: "Scenario 3"
  hosts: lxc2
  tasks:
    - name: Common packages
      apt:
        pkg:
          - rsync

    - name: Create app dir
      become: true
      become_user: user
      ansible.builtin.file:
        path: /home/user/app
        state: directory
        mode: '0755'
      ignore_errors: true

    - name: Copy over docker compose
      become: true
      become_user: user
      ansible.builtin.template:
        src: ../templates/app2/docker-compose.yml
        dest: /home/user/app/docker-compose.yml

    - name: Copy over Dockerfile
      ansible.posix.synchronize:
        src: ../templates/app2/Dockerfile
        dest: /home/user/app/Dockerfile
        recursive: true

    - name: Copy loop script
      ansible.posix.synchronize:
        src: ../templates/samba_write_loop.sh
        dest: /home/user/app/
      tags: ["rsync"]

    - name: Change perms
      ansible.builtin.file:
        path: /home/user/app
        state: directory
        recurse: yes
        owner: user
        group: sambausers
      tags: ["rsync"]

    - name: Start docker compose
      become: true
      become_user: user
      shell: 
        cmd: docker compose up -d
        chdir: /home/user/app

